### ISSUE TITLE
No Grammar.txt

### ISSUE THREAD

**Issue by Caleb-J773** [BrunoTh/ETS2Autopilot#1]
Collecting olefile (from pillow)
  Downloading olefile-0.44.zip (74kB)
    100% |################################| 81kB 5.1MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\olefile.egg-info
    writing top-level names to pip-egg-info\olefile.egg-info\top_level.txt
    writing pip-egg-info\olefile.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\olefile.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\olefile.egg-info\SOURCES.txt'
    error: [Errno 2] No such file or directory: 'C:\\Users\\User1\\Downloads\\ETS2Autopilot-master\\ETS2Autopilot-master\\python\\python35.zip\\lib2to3\\Grammar.txt'

**Comment by BrunoTh** [comment]
Sorry. That's a known problem. I forgot to add the workaround to the README.
To fix this error you simply have to rename the file python35.zip in the python\ directory and extract the content of the ZIP-file into a folder named python35.zip.

**Comment by Caleb-J773** [comment]
Hey thanks for the fast response to my question 👍 

I did what you said and re-ran the requirements and it looks like it installed everything correctly, i'll let you know if I get any more issues.

**Comment by BrunoTh** [comment]
Good to hear.
Thank you!
