### ISSUE TITLE
Question about ROI

### ISSUE THREAD

**Issue by zappybiby** [BrunoTh/ETS2Autopilot#4]
First just wanted to say what an awesome project!!

I wanted to know if you thought it might be beneficial to change the default ROI from the windscreen of the ["driver seat" camera](https://www.youtube.com/watch?v=4pzAbGT0PQg) to the "bumper" camera.

Since it seems the GUI wants us to set the area to fit the windscreen, it seems like going directly using the bumper camera make more consistent recordings from the same angle.

See an example of my ETS2 autopilot: https://www.youtube.com/watch?v=DYe3aTquavc

One disadvantage to this would be that it would increase the ROI area (and subsequently decrease performance) to cover the larger width that the roads take up from that perspective. We used OpenCV's `getPerspectiveTransform` to manage that since we found lanes using Hough Lines but I guess TensorFlow wouldn't really benefit from that as much.

**Comment by Caleb-J773** [comment]
This seems like a interesting idea. Bumper camera would allow tensorflow to see more of the road and lanes and without angle problems.   I thought about bumper camera too heh.

**Comment by BrunoTh** [comment]
At the very first beginning I also thought about this position. I rejected this idea because it was hard to play with this camera. But you can try it out and share the result with us. I'm a bit curious :D
