### ISSUE TITLE
Modifying model.py script for new deep learning model

### ISSUE THREAD

**Issue by apclypsr** [BrunoTh/ETS2Autopilot#6]
Hi Bruno,

I am wondering if it is possible to modify the model.py script with a different CNN structure (say, adding more filters) and rebuild the package myself to achieve different results from the same training data. Let me know if this is possible.

Thanks,
Lou

**Comment by BrunoTh** [comment]
Hi Lou,

Sorry for the late response. Had to write some exams.
Short answer is: It is possible. Only the input shape (x) has to stay the same or you have to change it in the other parts of the code.
After making changes you have to train the NN again.

Bruno

**Comment by apclypsr** [comment]
Thanks Bruno!
